logic/__init__.py
# logic/__init__.py

from flask import Blueprint
from logic.database import init_database

# Initialize the database
init_database()

bp = Blueprint('main_app', __name__)

from logic.routes.index import landing_page
from logic.routes.email_interest import display_order_confirmation
from logic.routes.free_pair import display_free_pair
from logic.routes.complete_order import display_complete_order

# Add URL rules to the blueprint
bp.add_url_rule('/', 'landing_page', landing_page)
bp.add_url_rule('/order_confirmation', 'display_order_confirmation', display_order_confirmation)
bp.add_url_rule('/free_pair', 'display_free_pair', display_free_pair)
# bp.add_url_rule('/complete_order', 'display_complete_order', display_complete_order)

logic/routes/admin.py
from flask import render_template, current_app, Blueprint, request, redirect, g, session, url_for
from logic.database import fetch_user_data, fetch_order_data, init_database
from logic.send_email import send_shipping_email
import sqlite3
import os

admin_bp = Blueprint('admin', __name__)

ADMIN_USERNAME = 'admin'
ADMIN_PASSWORD = 'Hasten123456$'

@admin_bp.route('/admin', methods=['GET', 'POST'])
def display_admin():

    # Check if the user is already authenticated
    if not session.get('logged_in'):
        # If not authenticated, check if the login form is submitted
        if request.method == 'POST':
            username = request.form.get('username')
            password = request.form.get('password')

            # Check the entered credentials against hardcoded values (demo purposes)
            if username == ADMIN_USERNAME and password == ADMIN_PASSWORD:
                # Set the user as authenticated
                session['logged_in'] = True
                return redirect(url_for('admin.display_admin'))  # Redirect to admin page upon successful login
            else:
                return render_template('login.html', login_error='Invalid credentials')
         # If not authenticated and no login form submitted, render the login page
        return render_template('login.html')



    user_data = fetch_user_data()
    order_data = fetch_order_data()

    DATABASE_PATH = 'single_database.db'

    customer_info = None  # Initialize customer_info outside the if block

    if request.method == 'POST':
        order = request.form.get('orderInfo')
        tracking = request.form.get('trackingNumber')
        
        customer_info = fetch_customer_info(order)
        g.db.close()
        send_shipping_email(customer_info, order, tracking)

    return render_template('admin.html', template_folder=current_app.template_folder, user_data=user_data, order_data=order_data, customer_info=customer_info)


def fetch_customer_info(order_info):
    # Use Flask's g object for handling database connections
    DATABASE_PATH = 'single_database.db'

    if 'db' not in g:
        g.db = sqlite3.connect(DATABASE_PATH)
    conn = g.db
    cursor = conn.cursor()

    cursor.execute('''
        SELECT size, color, name, address, city, state, zip, email
        FROM order_data
        WHERE order_info = ?
    ''', (order_info,))

    customer_info = cursor.fetchone()

    return customer_info

logic/routes/complete_order.py
from flask import render_template, current_app, Blueprint, request, redirect

complete_order_bp = Blueprint('complete_order', __name__)

@complete_order_bp.route('/complete_order', methods=['GET', 'POST'])
def display_complete_order():
    return render_template ('complete_order.html', template_folder=current_app.template_folder)

logic/routes/email_interest.py
from flask import Blueprint, render_template, request, redirect, url_for, current_app
from logic import bp

email_interest = Blueprint('email_interest', __name__)

@bp.route('/email_interest', methods=['GET', 'POST'])
def display_order_confirmation():
    return render_template('email_shipping.html', template_folder=current_app.template_folder)

logic/routes/free_pair.py
from flask import Blueprint, render_template, request, current_app, redirect, url_for
from logic.database import store_order_data
from logic.send_email import send_confirmation_email

free_pair_bp = Blueprint('free_pair', __name__)

@free_pair_bp.route('/free_pair', methods=['GET', 'POST'])
def display_free_pair():
    current_app.logger.info('Request Content: %s', request.get_data())

    # name_param = request.args.get('name', '')
    # email_param = request.args.get('email', '')

    if request.method == 'POST':
        # Handle form submission
        name = request.form.get('name')
        email = request.form.get('email')
        order_info = request.form.get('order_info')
        color = request.form.get('color')
        size = request.form.get('size')
        address = request.form.get('address')
        state = request.form.get('state')
        city = request.form.get('city')
        zip = request.form.get('zip')

        # Store the form data in the database
        store_order_data(name, email, order_info, color, size, address, state, city, zip)

        # send confirmation email
        send_confirmation_email(name, email, order_info, color, size, address, state, city, zip)

        # Redirect to the complete order page after processing the form
        return redirect(url_for('complete_order.display_complete_order'))


    # Render the template for GET requests
    return render_template('free_pair.html', template_folder=current_app.template_folder)

logic/routes/index.py
from flask import render_template, redirect, url_for, request, current_app, render_template_string, Blueprint
from logic import bp
from logic.database import store_user_data
from logic.send_email import send_interest_email

@bp.route('/', methods=['GET', 'POST'])
def landing_page():
    # Implementation for landing page and form submission
    if request.method == 'POST':
        # Handle form submission
        name = request.form.get('name')
        email = request.form.get('email')

        # Server-side validation
        if not name or not email:
            error_message = "Please fill out all required fields."
            return render_template('index.html', error_message=error_message)

        # Store the form data in the database
        store_user_data(name, email)

        # send interest email
        send_interest_email(name, email)

        # Render a temporary page with a message
        message = "Thank you for your interest in our Cleat Covers. You will be redirected to our Amazon Store shortly."
        return render_template('temp_page.html', message=message, name=name)


    # Render the HTML index template
    return render_template('index.html', template_folder=current_app.template_folder)


temp_bp = Blueprint('temp_page', __name__)

@temp_bp.route('/temporary_page')
def temporary_page():
    name = request.args.get('name', '')
    return render_template('temp_page.html')




@bp.route('/redirect_to_amazon')
def redirect_to_amazon():
    # Add a 5-second delay using JavaScript for client-side redirection
    js_redirect = """
    <script>
        setTimeout(function() {
            window.location.href = "{{ amazon_link }}";
        }, 200);  // 1-second delay
    </script>
    """
    return render_template_string(js_redirect, amazon_link='https://www.amazon.com/dp/B0CHMVWB1P')

logic/templates/admin.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Admin Page</title>
</head>
<body>

    <h1>User Data</h1>
    <table border="1">
        <thead>
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Email</th>
                <th>Timestamp</th>
            </tr>
        </thead>
        <tbody>
        
            {% for user_row in user_data %}
                <tr>
                    <td>{{ user_row[0] }}</td>
                    <td>{{ user_row[1] }}</td>
                    <td>{{ user_row[2] }}</td>
                    <td>{{ user_row[3] }}</td>
                </tr>
            {% endfor %}
        
        </tbody>
    </table>
    <h1>Order Data</h1>
    <table border="1">
        <thead>
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Email</th>
                <th>Order Info</th>
                <th>Color</th>
                <th>Size</th>
                <th>Address</th>
                <th>State</th>
                <th>City</th>
                <th>Zip</th>
                <th>Timestamp</th>
            </tr>
        </thead>
        <tbody>
            {% for order_row in order_data %}
                <tr>
                    <td>{{ order_row[0] }}</td>
                    <td>{{ order_row[1] }}</td>
                    <td>{{ order_row[2] }}</td>
                    <td>{{ order_row[3] }}</td>
                    <td>{{ order_row[4] }}</td>
                    <td>{{ order_row[5] }}</td>
                    <td>{{ order_row[6] }}</td>
                    <td>{{ order_row[7] }}</td>
                    <td>{{ order_row[8] }}</td>
                    <td>{{ order_row[9] }}</td>
                    <td>{{ order_row[10] }}</td>
                    <td>{{ order_row[11] }}</td>


                </tr>
            {% endfor %}
        </tbody>
    </table>
    <br>
    <h1>Shipping</h1>

    <form action="#" method="post">
        <label for="orderInfo">Order Info:</label>
        <input type="text" id="orderInfo" name="orderInfo" required>
        <br>

        <label for="trackingNumber">Tracking Number:</label>
        <input type="text" id="trackingNumber" name="trackingNumber" required>
        <br>

        <!-- <label for="email">Email:</label>
        <input type="email" id="email" name="email" required>
        <br> -->

        <input type="submit" value="Submit">
    </form>

        <!-- Display customer_info on the HTML page -->
    {% if customer_info %}
    <p>Size: {{ customer_info[0] }}</p>
    <p>Color: {{ customer_info[1] }}</p>    
    <p>Name: {{ customer_info[2] }}</p>
    <p>Address: {{ customer_info[3] }}</p>
    <p>City: {{ customer_info[4] }}</p>
    <p>State: {{ customer_info[5] }}</p>
    <p>Zip: {{ customer_info[6] }}</p>
    <p>Email: {{ customer_info[7] }}</p>
    {% else %}
    <p>No customer information available for the specified order.</p>
    {% endif %}

</body>
</html>

logic/templates/complete_order.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="HAS10 - Football cleat covers promotion">
    <meta name="author" content="Ansonika">
    <title>HAS10 | Football cleat covers promo</title>

    <!-- Favicons-->
    <link rel="shortcut icon" href="{{ url_for('static', filename='img/apple-touch-icon-72x72-precomposed.png') }}" type="image/x-icon">
	<link rel="apple-touch-icon" type="image/x-icon" sizes="72x72" href="{{ url_for('static', filename='img/apple-touch-icon-72x72-precomposed.png') }}">

    <!-- GOOGLE WEB FONT -->
    <link href="https://fonts.googleapis.com/css?family=Work+Sans:400,500,600" rel="stylesheet">

    <!-- BASE CSS -->
    <link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet">
	
    <link href="{{ url_for('static', filename='css/style.css') }}" rel="stylesheet">
	<link href="{{ url_for('static', filename='css/vendors.css') }}" rel="stylesheet"> 

    <!-- YOUR CUSTOM CSS -->
    <link href="{{ url_for('static', filename='css/custom.css') }}" rel="stylesheet">

	
	<!-- MODERNIZR MENU -->
	

</head>

<body>
	
	<div id="preloader">
		<div data-loader="circle-side"></div>
	</div><!-- /Preload -->
	
	<div id="loader_form">
		<div data-loader="circle-side-2"></div>
	</div><!-- /loader_form -->
	
	
	<!-- /menu -->
	
	<div class="container-fluid">
	    <div class="row row-height">
	        
	        <!-- /content-left -->
	        <div class="col-xl-8 col-lg-8 content-right" id="start">
	            <div id="wizard_container">
	                <div id="top-wizard">
	                    <span id="location"></span>
	                   
	                </div>
	                <!-- /top-wizard -->
	                <form id="wrapped" method="post" enctype="multipart/form-data">
	                    <input id="website" name="website" type="text" value="">
	                    <!-- Leave for security protection, read docs for details -->
	                    <div>
	                        <div>
								<div>
									<h2 class="section_title">🎉 Thanks for your purchase.</h2>
									<h2 class="section_title">We've secured your details for the free cleat covers promo.</h2>
									<h3 class="main_question">Your order is set to ship within 24-48 hours and we'll send an email with the tracking details.</h3>  
	                        </div>
	                    </div>
	                    <!-- /middle-wizard -->
	                    
	                    <!-- /bottom-wizard -->
	                </form>
	            </div>
	            <!-- /Wizard container -->
	        </div>
	        <!-- /content-right-->
	    </div>
	    <!-- /row-->
	</div>
	<!-- /container-fluid -->

	<div class="cd-overlay-nav">
		<span></span>
	</div>
	<!-- /cd-overlay-nav -->

	<div class="cd-overlay-content">
		<span></span>
	</div>
	<!-- /cd-overlay-content -->
	
	<!-- COMMON SCRIPTS -->
	<script src="{{ url_for('static', filename='js/jquery-3.7.1.min.js') }}"></script>
	<script src="{{ url_for('static', filename='js/common_scripts.min.js') }}"></script>
	<script src="{{ url_for('static', filename='js/velocity.min.js') }}"></script>
	<script src="{{ url_for('static', filename='js/common_functions.js') }}"></script>
	<script src="{{ url_for('static', filename='js/file-validator.js') }}"></script>

	<!-- Wizard script-->
	<!-- <script src="{{ url_for('static', filename='js/func_1.js') }}"></script> -->


</body>
</html>

logic/templates/free_pair.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="HAS10 - Football cleat covers promotion">
    <meta name="author" content="Ansonika">
    <title>HAS10 | Football cleat covers promo</title>

    <!-- Favicons-->
    <link rel="shortcut icon" href="img/apple-touch-icon-72x72-precomposed.png" type="image/x-icon">
    <link rel="apple-touch-icon" type="image/x-icon" sizes="72x72" href="img/apple-touch-icon-72x72-precomposed.png">

    <!-- GOOGLE WEB FONT -->
    <link href="https://fonts.googleapis.com/css?family=Work+Sans:400,500,600" rel="stylesheet">

    <!-- BASE CSS -->
	<link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet">
	<link href="{{ url_for('static', filename='css/style.css') }}" rel="stylesheet">
	<link href="{{ url_for('static', filename='css/vendors.css') }}" rel="stylesheet">
	

    <!-- YOUR CUSTOM CSS -->
    <link href="{{ url_for('static', filename='css/custom.css') }}" rel="stylesheet">
	
	<!-- MODERNIZR MENU -->
	

</head>

<body>
	
	<div id="preloader">
		<div data-loader="circle-side"></div>
	</div><!-- /Preload -->
	
	<div id="loader_form">
		<div data-loader="circle-side-2"></div>
	</div><!-- /loader_form -->
	
	
	<!-- /menu -->
	
	<div class="container-fluid">
	    <div class="row row-height">
	        <div class="col-xl-4 col-lg-4 content-left">
	            <div class="content-left-wrapper">
	                <a href="https://www.amazon.com/dp/B0CHMVWB1P" id="logo"><img src="{{ url_for('static', filename='img/logo.png') }}" alt="" width="45" height="45"></a>

	                <div>
	                    <figure><img src="{{ url_for('static', filename='img/HAS10-football-spats.png') }}" alt="" class="img" width="270" height="270"></figure>
	                    <h2>Thank you for your purchase</h2>
	                    <p>Provide the following details to claim your FREE pair cleat covers.</p>
	                    
	                    
	                </div>
	                <div class="copy">© 2024 HAS10</div>
	            </div>
	            <!-- /content-left-wrapper -->
	        </div>
	        <!-- /content-left -->
	        <div class="col-xl-8 col-lg-8 content-right" id="start">
	            <div id="wizard_container">
	                <div id="top-wizard">
	                    <span id="location"></span>
	                   
	                </div>
	                <!-- /top-wizard -->
	                <form id="wrapped" method="post" action="{{ url_for('main_app.display_free_pair') }}" enctype="multipart/form-data">
	                    <input id="website" name="website" type="text" value="">
	                    <!-- Leave for security protection, read docs for details -->
	                    <div>
	                        <div>
								<div>
								</div>
	                            <h2 class="section_title">Amazon order number</h2>
	                            <p class="main_question">You can find the order number on the amazon purchase email or <a href="https://www.amazon.com/gp/css/order-history">click here</a> to view your amazon orders.</p>
								</div>
								
								
								<div>
	                            <div class="form-group add_top_30">
	                                <label for="order">Amazon order number</label>
	                                <input type="text" name="order_info" id="order_info" class="form-control required" onchange="getVals(this, 'name_field');" required>
	                            </div>
								<div class="form-group add_bottom_30">
									<h2 class="section_title">Select your FREE cleat covers</h2>
									<label>Cleat covers</label>
									<label for="size">size</label>
									<div class="styled-select clearfix">
										<select class="form-control required" name="size" id="size" required>
											<option value="">Choose a size</option>
											<option value="Youth">Youth</option>
											<option value="Small/Medium">Small/Medium</option>
											<option value="Large">Large</option>
										</select>
									</div>
								</div>
								<div class="form-group add_bottom_30">
									<label>Cleat covers</label>
									<label for="color">color</label>
									<div class="styled-select clearfix">
										<select class="form-control required" name="color" id="color" required>
											<option value="">Choose a color</option>
											<option value="Black">Black</option>
											<option value="White">White</option>
											<option value="Orange">Orange</option>
											<option value="Red">Red</option>
											<option value="Royal Blue">Royal Blue</option>
										</select>
									</div>
								</div>
	                            
								<div class="form-group">
									<h2 class="section_title">Shipping information</h2>
	                                <label for="name">Full name</label>
	                                <input type="name" name="name" id="name" class="form-control required" onchange="getVals(this, 'name_field');" required>
	                            </div>

								<div class="form-group">
									<label for="email">Email</label>
									<input type="email" name="email" id="email" class="form-control required" onchange="getVals(this, 'email_field');" required>
								</div>
								
								
								<div class="form-group">
	                                <label for="address">Address</label>
	                                <input type="address" name="address" id="address" class="form-control required" onchange="getVals(this, 'address_field');" required>
	                            </div>
								<div class="form-group">
	                                <label for="city">City</label>
	                                <input type="city" name="city" id="city" class="form-control required" onchange="getVals(this, 'city_field');" required>
	                            </div>
								<div class="form-group">
	                                <label for="state">State</label>
	                                <input type="state" name="state" id="state" class="form-control required" onchange="getVals(this, 'state_field');" required>
	                            </div>
								<div class="form-group">
	                                <label for="zip">Zip code</label>
	                                <input type="zip" name="zip" id="zip" class="form-control required" onchange="getVals(this, 'zip_field');" required>
	                            </div>
								
								<div id="bottom-wizard">
	                        
									<button type="submit" name="process" class="submit">Submit</button>
								</div>
				
	                            
	                        </div>
	                        

	                    </div>
	                    <!-- /middle-wizard -->
	                    
	                    <!-- /bottom-wizard -->
	                </form>
	            </div>
	            <!-- /Wizard container -->
	        </div>
	        <!-- /content-right-->
	    </div>
	    <!-- /row-->
	</div>
	<!-- /container-fluid -->

	<div class="cd-overlay-nav">
		<span></span>
	</div>
	<!-- /cd-overlay-nav -->

	<div class="cd-overlay-content">
		<span></span>
	</div>
	<!-- /cd-overlay-content -->

	
	<!-- COMMON SCRIPTS -->
	<script src="{{ url_for('static', filename='js/jquery-3.7.1.min.js') }}"></script>
	<script src="{{ url_for('static', filename='js/common_scripts.min.js') }}"></script>
	<script src="{{ url_for('static', filename='js/velocity.min.js') }}"></script>
	<script src="{{ url_for('static', filename='js/common_functions.js') }}"></script>
	<script src="{{ url_for('static', filename='js/file-validator.js') }}"></script>


	<!-- Wizard script-->
	<!-- <script src="js/func_1.js"></script> -->

</body>
</html>

logic/templates/index.html
 <!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="HAS10 - Football cleat covers promotion">
    <meta name="author" content="Ansonika">
    <title>HAS10 | Football cleat covers promo</title>

    <!-- Favicons-->
    <link rel="shortcut icon" href="{{ url_for('static', filename='img/apple-touch-icon-72x72-precomposed.png') }}" type="image/x-icon">
	<link rel="apple-touch-icon" type="image/x-icon" sizes="72x72" href="{{ url_for('static', filename='img/apple-touch-icon-72x72-precomposed.png') }}">

    <!-- GOOGLE WEB FONT -->
    <link href="https://fonts.googleapis.com/css?family=Work+Sans:400,500,600" rel="stylesheet">

    <!-- BASE CSS -->
    <link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet">
	
    <link href="{{ url_for('static', filename='css/style.css') }}" rel="stylesheet">
	<link href="{{ url_for('static', filename='css/vendors.css') }}" rel="stylesheet"> 

    <!-- YOUR CUSTOM CSS -->
    <link href="{{ url_for('static', filename='css/custom.css') }}" rel="stylesheet">

	
	<!-- MODERNIZR MENU -->
	

</head>

<body>
	
	<div id="preloader">
		<div data-loader="circle-side"></div>
	</div><!-- /Preload -->
	
	<div id="loader_form">
		<div data-loader="circle-side-2"></div>
	</div><!-- /loader_form -->
	
	
	<!-- /menu -->
	
	<div class="container-fluid">
	    <div class="row row-height">
	        <div class="col-xl-4 col-lg-4 content-left">
	            <div class="content-left-wrapper">
					<a href="https://www.amazon.com/dp/B0CHMVWB1P" id="logo"><img src="{{ url_for('static', filename='img/logo.png') }}" alt="" width="45" height="45"></a>
	                
	                <div>
	                    <figure><img src="{{ url_for('static', filename='img/HAS10-football-spats.png') }}" alt="" class="img" width="270" height="270"></figure>
	                    <h2>Get a free pair of cleat covers</h2>
	                    <p>Buy a pair of football cleat covers from our Amazon store and provide proof of purchase and we'll send you a FREE pair.</p>
	                    
	                    
	                </div>
	                <div class="copy">© 2024 HAS10</div>
	            </div>
	            <!-- /content-left-wrapper -->
	        </div>
	        <!-- /content-left -->
	        <div class="col-xl-8 col-lg-8 content-right" id="start">
	            <div id="wizard_container">
	                <div id="top-wizard">
	                    <span id="location"></span>
	                   
	                </div>
	                <!-- /top-wizard -->
					<form id="wrapped" method="post" enctype="multipart/form-data" action="{{ url_for('main_app.landing_page') }}">


	                    <input id="website" name="website" type="text" value="">
	                    <!-- Leave for security protection, read docs for details -->
	                    <div>
	                        <div>
								<div>
									<h3 class="main_question">Exclusive Offer: Buy a Pair, Get a Pair on Us!</h3>
								</div>
	                            <h2 class="section_title">Step 1</h2>
	                            <p class="main_question">Enter name and email, then continue to Amazon.com to purchase a pair of cleat covers.</p>
								</div>
								
								<div>
	                            <div class="form-group add_top_30">
	                                <label for="name">First and Last Name</label>
	                                <input type="text" name="name" id="name" class="form-control required" onchange="getVals(this, 'name_field');">
	                            </div>
	                            <div class="form-group">
	                                <label for="email">Email Address</label>
	                                <input type="email" name="email" id="email" class="form-control required" onchange="getVals(this, 'email_field');">
	                            </div>
								<div id="bottom-wizard">
	                        
									<button type="submit" name="process" class="submit">Submit and Continue to Amazon</button>
								</div>
								<div>
									<h2 class="section_title">Step 2 (Next)</h2>
									<p class="main_question">Provide order and shipping details. </p>
									<p class="main_question">After submitting this form you'll receive an email from us with instructions to provide the order number and shipping details.</p>
									</div>
	                            
	                        </div>
	                        

	                    </div>
	                    <!-- /middle-wizard -->
	                    
	                    <!-- /bottom-wizard -->
	                </form>
	            </div>
	            <!-- /Wizard container -->
	        </div>
	        <!-- /content-right-->
	    </div>
	    <!-- /row-->
	</div>
	<!-- /container-fluid -->

	<div class="cd-overlay-nav">
		<span></span>
	</div>
	<!-- /cd-overlay-nav -->

	<div class="cd-overlay-content">
		<span></span>
	</div>
	<!-- /cd-overlay-content -->
	
	<!-- COMMON SCRIPTS -->
	<script src="{{ url_for('static', filename='js/jquery-3.7.1.min.js') }}"></script>
	<script src="{{ url_for('static', filename='js/common_scripts.min.js') }}"></script>
	<script src="{{ url_for('static', filename='js/velocity.min.js') }}"></script>
	<script src="{{ url_for('static', filename='js/common_functions.js') }}"></script>
	<script src="{{ url_for('static', filename='js/file-validator.js') }}"></script>

	<!-- Wizard script-->
	<!-- <script src="{{ url_for('static', filename='js/func_1.js') }}"></script> -->


</body>
</html>

logic/templates/temp_page.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="HAS10 - Football cleat covers promotion">
    <meta name="author" content="Ansonika">
    <title>HAS10 | Football cleat covers promo</title>

    <!-- Favicons-->
    <link rel="shortcut icon" href="{{ url_for('static', filename='img/apple-touch-icon-72x72-precomposed.png') }}" type="image/x-icon">
	<link rel="apple-touch-icon" type="image/x-icon" sizes="72x72" href="{{ url_for('static', filename='img/apple-touch-icon-72x72-precomposed.png') }}">

    <!-- GOOGLE WEB FONT -->
    <link href="https://fonts.googleapis.com/css?family=Work+Sans:400,500,600" rel="stylesheet">

    <!-- BASE CSS -->
    <link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet">
	
    <link href="{{ url_for('static', filename='css/style.css') }}" rel="stylesheet">
	<link href="{{ url_for('static', filename='css/vendors.css') }}" rel="stylesheet"> 

    <!-- YOUR CUSTOM CSS -->
    <link href="{{ url_for('static', filename='css/custom.css') }}" rel="stylesheet">

	
	<!-- MODERNIZR MENU -->
	

</head>

<body>
	
	<div id="preloader">
		<div data-loader="circle-side"></div>
	</div><!-- /Preload -->
	
	<div id="loader_form">
		<div data-loader="circle-side-2"></div>
	</div><!-- /loader_form -->
	
	
	<!-- /menu -->
	
	<div class="container-fluid">
	    <div class="row row-height">
	        
	        <!-- /content-left -->
	        <div class="col-xl-8 col-lg-8 content-right" id="start">
	            <div id="wizard_container">
	                <div id="top-wizard">
	                    <span id="location"></span>
	                   
	                </div>
	                <!-- /top-wizard -->
	                <form id="wrapped" method="post" enctype="multipart/form-data">
	                    <input id="website" name="website" type="text" value="">
	                    <!-- Leave for security protection, read docs for details -->
	                    <div>
	                        <div>
								<div>
									<h2 class="section_title">Thank you, check your email for instructions.</h2>
									
									
								</div>
	                            <p class="main_question">We're redirecting you to our Amazon store...</p>
								<p class="main_question">If you're not redirected,<a href="https://www.amazon.com/dp/B0CHMVPCC7?ref=myi_title_dp" target="_blank"> access our store here.</a></p>
								</div>
								
								
								
	                            
	                        </div>
	                        

	                    </div>
	                    <!-- /middle-wizard -->
	                    
	                    <!-- /bottom-wizard -->
	                </form>
	            </div>
	            <!-- /Wizard container -->
	        </div>
	        <!-- /content-right-->
	    </div>
	    <!-- /row-->
	</div>
	<!-- /container-fluid -->

	<div class="cd-overlay-nav">
		<span></span>
	</div>
	<!-- /cd-overlay-nav -->

	<div class="cd-overlay-content">
		<span></span>
	</div>
	<!-- /cd-overlay-content -->
	
	<!-- COMMON SCRIPTS -->
	<script src="{{ url_for('static', filename='js/jquery-3.7.1.min.js') }}"></script>
	<script src="{{ url_for('static', filename='js/common_scripts.min.js') }}"></script>
	<script src="{{ url_for('static', filename='js/velocity.min.js') }}"></script>
	<script src="{{ url_for('static', filename='js/common_functions.js') }}"></script>
	<script src="{{ url_for('static', filename='js/file-validator.js') }}"></script>

	<!-- Wizard script-->
	<!-- <script src="{{ url_for('static', filename='js/func_1.js') }}"></script> -->

     <!-- JavaScript for client-side redirection -->
     <script>
        setTimeout(function() {
            window.location.href = "{{ url_for('main_app.redirect_to_amazon') }}";
        }, 5000);  // 5-second delay
    </script>


</body>
</html>